# Generated by Django 3.0.7 on 2020-06-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='titulo',
            new_name='title',
        ),
    ]
